const express = require('express')
const { signUp, signIn, Read,Delete,getImage,Update } = require('../Controllers/controller')
const Router = express.Router()
Router.post('/signup',signUp)
Router.post('/signin',signIn)
Router.get('/read',Read)
Router.get('/getimage/:imagename',getImage)
Router.put('/update/:id',Update)
Router.delete('/delete/:id',Delete)
module.exports = Router;
